### ISSUE TITLE
make Certifications show with a button

### ISSUE THREAD

**Issue by Sboonny** [Sboonny/portfolio#3]
add the third certification and make all of them in section of their own, that is interactable

**Comment by kartikgajjar7** [comment]
hey sboonny... can you explain more about this issue i can work on it :)

**Comment by Sboonny** [comment]
@Kartik2220 thank you for taking interest in clearing it, but this isn't a real issue but more like documentation for myself.

There is an animation issue in https://github.com/Sboonny/portfolio/blob/main/assests/styles.css

It isn't optimized and buggy, if you got a moment to alter it I would appreciate.

**Comment by Sboonny** [comment]
Showcasing certification isn't a something that is interesting for me anymore
